version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./utils/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    env_file:
      .env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - 3306:3306
    expose:
      - 3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true