version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlcontainer
    restart: always
    volumes:
      - ./utils/init:/docker-entrypoint-initdb.d/init.sql
      - $HOME/database:/var/lib/mysql
    build: .
    env_file:
      .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306

  app:
    container_name: solvd_shop_api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    links:
      - db
    tty: true
    volumes:
      - ./:/src

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
volumes:
  container-volume: